# Generated by Django 3.2.12 on 2024-05-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240511_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_admin',
            new_name='is_staff',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
