# Generated by Django 5.0.4 on 2024-05-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_auto_20240511_1809"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="is_staff",
            new_name="is_staff_property",
        ),
    ]
