# Generated by Django 5.0.4 on 2024-05-12 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_customer_groups_customer_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator("Invalid email address")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "password can't be empty"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "Username can't be empty"
                    )
                ],
            ),
        ),
    ]
