# Generated by Django 5.0.4 on 2024-05-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0011_alter_customer_email_alter_customer_password_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["username"], name="username_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="email_idx"),
        ),
    ]
