# Generated by Django 5.0.4 on 2024-05-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_customer_username_idx_customer_email_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user_permissions",
        ),
    ]
