# Generated by Django 5.0.4 on 2024-05-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_rename_is_staff_property_customer__is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="_is_staff",
            new_name="is_staff",
        ),
    ]
